# # # # # # # # # # # # # # # # # # Logback Start # # # # # # # # # # # # # # # # # #
# 配置logback
logging:
  # 输入的日志文件路径，哪个文件夹下
  path: dirName/log
  # 日志文件的名字
  file: logInfo
  # 关联的配置文件，名字不要更改
  config: classpath:logback-spring.xml
# # # # # # # # # # # # # # # # # # Logback Start # # # # # # # # # # # # # # # # # #